<?php

namespace Database\Seeders;

use App\Exports\Reports\Booking;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bookings = [
            [
                'booking_id' => 'BKG001',
                'user_id' => 'USR001',
                'hotel_id' => 'HTL001',
                'order_id' => 'ORD001',
                'booking_type' => 'Deluxe',
                'name' => 'John Doe',
                'amount' => '5000',
                'email' => 'johndoe@example.com',
                'primary_phone_number' => '1234567890',
                'secondary_phone_number' => '0987654321',
                'notes' => 'Check-in at 2 PM',
                'check_in' => '2023-05-01 14:00:00',
                'check_out' => '2023-05-05 11:00:00',
                'check_in_hours' => '24',
                'check_in_time' => '14:00:00',
                'razorpay_payment_id' => 'RZP001',
                'razorpay_signature' => 'SIG001',
                'payment_status' => 'Paid',
                'payment_method' => 'online',
                'is_cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'room_rate' => 4000,
                'extra_guest_charge' => 500,
                'platform_fee' => 100,
                'convenience_fee' => 50,
                'transfer_id' => 'TRF001',
                'transfer_status' => 'Completed',
                'coupon_id' => null,
                'guest_name' => 'Jane Doe',
            ],
            [
                'booking_id' => 'BKG002',
                'user_id' => 'USR002',
                'hotel_id' => 'HTL002',
                'order_id' => 'ORD002',
                'booking_type' => 'Standard',
                'name' => 'Alice Smith',
                'amount' => '3000',
                'email' => 'alicesmith@example.com',
                'primary_phone_number' => '2345678901',
                'secondary_phone_number' => null,
                'notes' => 'Early check-in requested',
                'check_in' => '2023-05-10 12:00:00',
                'check_out' => '2023-05-12 10:00:00',
                'check_in_hours' => '24',
                'check_in_time' => '12:00:00',
                'razorpay_payment_id' => 'RZP002',
                'razorpay_signature' => 'SIG002',
                'payment_status' => 'Paid',
                'payment_method' => 'offline',
                'is_cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'room_rate' => 2500,
                'extra_guest_charge' => 300,
                'platform_fee' => 100,
                'convenience_fee' => 100,
                'transfer_id' => 'TRF002',
                'transfer_status' => 'Completed',
                'coupon_id' => null,
                'guest_name' => 'Bob Smith',
            ],
            // Add more entries below
            [
                'booking_id' => 'BKG003',
                'user_id' => 'USR003',
                'hotel_id' => 'HTL003',
                'order_id' => 'ORD003',
                'booking_type' => 'Suite',
                'name' => 'Emily Brown',
                'amount' => '7000',
                'email' => 'emilybrown@example.com',
                'primary_phone_number' => '3456789012',
                'secondary_phone_number' => '2109876543',
                'notes' => 'Late check-out requested',
                'check_in' => '2023-05-15 15:00:00',
                'check_out' => '2023-05-20 12:00:00',
                'check_in_hours' => '24',
                'check_in_time' => '15:00:00',
                'razorpay_payment_id' => 'RZP003',
                'razorpay_signature' => 'SIG003',
                'payment_status' => 'Pending',
                'payment_method' => 'online',
                'is_cancelled' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'room_rate' => 6000,
                'extra_guest_charge' => 800,
                'platform_fee' => 150,
                'convenience_fee' => 150,
                'transfer_id' => 'TRF003',
                'transfer_status' => 'Pending',
                'coupon_id' => null,
                'guest_name' => 'Michael Brown',
            ],
            [
                'booking_id' => 'BKG004',
                'user_id' => 'USR004',
                'hotel_id' => 'HTL004',
                'order_id' => 'ORD004',
                'booking_type' => 'Standard',
                'name' => 'Sarah Johnson',
                'amount' => '4000',
                'email' => 'sarahjohnson@example.com',
                'primary_phone_number' => '4567890123',
                'secondary_phone_number' => '3210987654',
                'notes' => 'Early check-in required',
                'check_in' => '2023-06-01 13:00:00',
                'check_out' => '2023-06-05 10:00:00',
                'check_in_hours' => '24',
                'check_in_time' => '13:00:00',
                'razorpay_payment_id' => 'RZP004',
                'razorpay_signature' => 'SIG004',
                'payment_status' => 'Paid',
                'payment_method' => 'online',
                'is_cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'room_rate' => 3500,
                'extra_guest_charge' => 400,
                'platform_fee' => 120,
                'convenience_fee' => 80,
                'transfer_id' => 'TRF004',
                'transfer_status' => 'Completed',
                'coupon_id' => null,
                'guest_name' => 'David Johnson',
            ],
            [
                'booking_id' => 'BKG005',
                'user_id' => 'USR005',
                'hotel_id' => 'HTL005',
                'order_id' => 'ORD005',
                'booking_type' => 'Deluxe',
                'name' => 'Emma Wilson',
                'amount' => '6000',
                'email' => 'emmawilson@example.com',
                'primary_phone_number' => '5678901234',
                'secondary_phone_number' => null,
                'notes' => 'Late check-out requested',
                'check_in' => '2023-06-10 14:00:00',
                'check_out' => '2023-06-15 12:00:00',
                'check_in_hours' => '24',
                'check_in_time' => '14:00:00',
                'razorpay_payment_id' => 'RZP005',
                'razorpay_signature' => 'SIG005',
                'payment_status' => 'Paid',
                'payment_method' => 'offline',
                'is_cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'room_rate' => 5000,
                'extra_guest_charge' => 600,
                'platform_fee' => 150,
                'convenience_fee' => 100,
                'transfer_id' => 'TRF005',
                'transfer_status' => 'Completed',
                'coupon_id' => null,
                'guest_name' => 'Olivia Wilson',
            ],
            [
                'booking_id' => 'BKG006',
                'user_id' => 'USR006',
                'hotel_id' => 'HTL006',
                'order_id' => 'ORD006',
                'booking_type' => 'Suite',
                'name' => 'Michael Garcia',
                'amount' => '8000',
                'email' => 'michaelgarcia@example.com',
                'primary_phone_number' => '6789012345',
                'secondary_phone_number' => '5432109876',
                'notes' => 'Special dietary requirements',
                'check_in' => '2023-06-20 13:00:00',
                'check_out' => '2023-06-25 11:00:00',
                'check_in_hours' => '24',
                'check_in_time' => '13:00:00',
                'razorpay_payment_id' => 'RZP006',
                'razorpay_signature' => 'SIG006',
                'payment_status' => 'Pending',
                'payment_method' => 'online',
                'is_cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'room_rate' => 7000,
                'extra_guest_charge' => 700,
                'platform_fee' => 200,
                'convenience_fee' => 150,
                'transfer_id' => 'TRF006',
                'transfer_status' => 'Pending',
                'coupon_id' => null,
                'guest_name' => 'Sophia Garcia',
            ],
            [
                'booking_id' => 'BKG007',
                'user_id' => 'USR007',
                'hotel_id' => 'HTL007',
                'order_id' => 'ORD007',
                'booking_type' => 'Standard',
                'name' => 'Daniel Martinez',
                'amount' => '3500',
                'email' => 'danielmartinez@example.com',
                'primary_phone_number' => '7890123456',
                'secondary_phone_number' => null,
                'notes' => 'Late arrival, arrange airport pickup',
                'check_in' => '2023-06-30 15:00:00',
                'check_out' => '2023-07-05 12:00:00',
                'check_in_hours' => '24',
                'check_in_time' => '15:00:00',
                'razorpay_payment_id' => 'RZP007',
                'razorpay_signature' => 'SIG007',
                'payment_status' => 'Paid',
                'payment_method' => 'offline',
                'is_cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'room_rate' => 3000,
                'extra_guest_charge' => 400,
                'platform_fee' => 100,
                'convenience_fee' => 80,
                'transfer_id' => 'TRF007',
                'transfer_status' => 'Completed',
                'coupon_id' => null,
                'guest_name' => 'Isabella Martinez',
            ],
            [
                'booking_id' => 'BKG008',
                'user_id' => 'USR008',
                'hotel_id' => 'HTL008',
                'order_id' => 'ORD008',
                'booking_type' => 'Standard',
                'name' => 'Oliver Thompson',
                'amount' => '4000',
                'email' => 'oliverthompson@example.com',
                'primary_phone_number' => '8901234567',
                'secondary_phone_number' => '7654321098',
                'notes' => 'Room preference: Non-smoking',
                'check_in' => '2023-07-10 12:00:00',
                'check_out' => '2023-07-15 10:00:00',
                'check_in_hours' => '24',
                'check_in_time' => '12:00:00',
                'razorpay_payment_id' => 'RZP008',
                'razorpay_signature' => 'SIG008',
                'payment_status' => 'Paid',
                'payment_method' => 'online',
                'is_cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'room_rate' => 3500,
                'extra_guest_charge' => 300,
                'platform_fee' => 100,
                'convenience_fee' => 80,
                'transfer_id' => 'TRF008',
                'transfer_status' => 'Completed',
                'coupon_id' => null,
                'guest_name' => 'Amelia Thompson',
            ],
            [
                'booking_id' => 'BKG009',
                'user_id' => 'USR009',
                'hotel_id' => 'HTL009',
                'order_id' => 'ORD009',
                'booking_type' => 'Deluxe',
                'name' => 'Lucas Harris',
                'amount' => '6000',
                'email' => 'lucasharris@example.com',
                'primary_phone_number' => '9012345678',
                'secondary_phone_number' => null,
                'notes' => 'Celebrating anniversary',
                'check_in' => '2023-07-20 14:00:00',
                'check_out' => '2023-07-25 12:00:00',
                'check_in_hours' => '24',
                'check_in_time' => '14:00:00',
                'razorpay_payment_id' => 'RZP009',
                'razorpay_signature' => 'SIG009',
                'payment_status' => 'Paid',
                'payment_method' => 'offline',
                'is_cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'room_rate' => 5000,
                'extra_guest_charge' => 500,
                'platform_fee' => 150,
                'convenience_fee' => 100,
                'transfer_id' => 'TRF009',
                'transfer_status' => 'Completed',
                'coupon_id' => null,
                'guest_name' => 'Mia Harris',
            ],
            [
                'booking_id' => 'BKG010',
                'user_id' => 'USR010',
                'hotel_id' => 'HTL010',
                'order_id' => 'ORD010',
                'booking_type' => 'Suite',
                'name' => 'Ethan Wilson',
                'amount' => '8000',
                'email' => 'ethanwilson@example.com',
                'primary_phone_number' => '0123456789',
                'secondary_phone_number' => '9876543210',
                'notes' => 'Require extra pillows',
                'check_in' => '2023-07-30 13:00:00',
                'check_out' => '2023-08-05 11:00:00',
                'check_in_hours' => '24',
                'check_in_time' => '13:00:00',
                'razorpay_payment_id' => 'RZP010',
                'razorpay_signature' => 'SIG010',
                'payment_status' => 'Pending',
                'payment_method' => 'online',
                'is_cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'room_rate' => 7000,
                'extra_guest_charge' => 700,
                'platform_fee' => 200,
                'convenience_fee' => 150,
                'transfer_id' => 'TRF010',
                'transfer_status' => 'Pending',
                'coupon_id' => null,
                'guest_name' => 'Ava Wilson',
            ],
            [
                'booking_id' => 'BKG011',
                'user_id' => 'USR011',
                'hotel_id' => 'HTL011',
                'order_id' => 'ORD011',
                'booking_type' => 'Standard',
                'name' => 'Alexander Lee',
                'amount' => '3500',
                'email' => 'alexanderlee@example.com',
                'primary_phone_number' => '1234567890',
                'secondary_phone_number' => null,
                'notes' => 'Require airport shuttle',
                'check_in' => '2023-08-10 15:00:00',
                'check_out' => '2023-08-15 12:00:00',
                'check_in_hours' => '24',
                'check_in_time' => '15:00:00',
                'razorpay_payment_id' => 'RZP011',
                'razorpay_signature' => 'SIG011',
                'payment_status' => 'Paid',
                'payment_method' => 'offline',
                'is_cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'room_rate' => 3000,
                'extra_guest_charge' => 400,
                'platform_fee' => 100,
                'convenience_fee' => 80,
                'transfer_id' => 'TRF011',
                'transfer_status' => 'Completed',
                'coupon_id' => null,
                'guest_name' => 'Charlotte Lee',
            ],
        ];

        foreach ($bookings as $booking) {
            DB::table('bookings')->insert($booking);
        }
    }
}
