<?php

namespace Database\Seeders;

use App\Models\Hotel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run()
    {
        $hotels = [
            [
                'vendor_id' => 1,
                'name' => 'Luxury Villa',
                'slug' => 'luxury-villa-9',
                'description' => 'Experience ultimate luxury and comfort in our exquisite villa, featuring stunning views and world-class amenities.',
                'property_type_id' => 2, // Assuming 2 represents Villa in your property type table
                'pay_in_property' => 1,
                'primary_number' => '1234567890',
                'secondary_number' => '0987654321',
                'primary_email' => 'info@luxuryvilla.com',
                'secondary_email' => 'reservations@luxuryvilla.com',
                'address' => '456 Ocean Drive',
                'city_id' => 2, // Assuming 2 represents a city in your city table
                'country' => 'United States',
                'zip' => '54321',
                'location_iframe' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d193595.58880897957!2d-73.97968070317583!3d40.69766372295083!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c2588f046ee661%3A0xa75e3cb439f6fb2e!2sMiami%2C%20FL%2C%20USA!5e0!3m2!1sen!2s!4v1634001673140!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
                'policies' => 'No smoking, Pets allowed with additional fee',
                'banner_image' => 'luxury-villa-banner.jpg',
                'tenancy_agreement' => 'tenancy-agreement.pdf',
                'corporate_documents' => 'corporate-documents.zip',
                'identity_documents' => 'identity-documents.zip',
                'proof_of_ownership' => 'proof-of-ownership.pdf',
                'isActive' => 1,
                'isVerified' => 1,
                'isBanned' => 0,
                'nearby_locations' => 'Beachfront, Golf Course',
            ],
            [
                'vendor_id' => 2,
                'name' => 'Mountain Retreat',
                'slug' => 'mountain-retreat-8',
                'description' => 'Escape to our secluded mountain retreat and reconnect with nature in our cozy cabins and lodges.',
                'property_type_id' => 3, // Assuming 3 represents Cabin/Lodge in your property type table
                'pay_in_property' => 1,
                'primary_number' => '2345678901',
                'secondary_number' => '9876543210',
                'primary_email' => 'info@mountainretreat.com',
                'secondary_email' => 'reservations@mountainretreat.com',
                'address' => '789 Pine Street',
                'city_id' => 3, // Assuming 3 represents a city in your city table
                'country' => 'United States',
                'zip' => '67890',
                'location_iframe' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d105962.0080109225!2d-105.27054531874083!3d39.739235831738656!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x876b80aa23616883%3A0x8c22b81b1fc3d1c9!2sDenver%2C%20CO%2C%20USA!5e0!3m2!1sen!2s!4v1634002160278!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
                'policies' => 'No smoking, No pets allowed',
                'banner_image' => 'mountain-retreat-banner.jpg',
                'tenancy_agreement' => 'tenancy-agreement.pdf',
                'corporate_documents' => 'corporate-documents.zip',
                'identity_documents' => 'identity-documents.zip',
                'proof_of_ownership' => 'proof-of-ownership.pdf',
                'isActive' => 1,
                'isVerified' => 1,
                'isBanned' => 0,
                'nearby_locations' => 'Hiking Trails, Ski Resorts',
            ],
            [
                'vendor_id' => 1,
                'name' => 'Serene Villa',
                'slug' => 'serene-villa-7',
                'description' => 'Escape to this luxurious villa surrounded by lush greenery and breathtaking views.',
                'property_type_id' => 2, // Assuming 2 represents Villa in your property type table
                'pay_in_property' => 1,
                'primary_number' => '1234567890',
                'secondary_number' => '0987654321',
                'primary_email' => 'info@serenevilla.com',
                'secondary_email' => 'reservations@serenevilla.com',
                'address' => '456 Oak Avenue',
                'city_id' => 2, // Assuming 2 represents a city in your city table
                'country' => 'United States',
                'zip' => '54321',
                'location_iframe' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3168.8130737346667!2d-122.43129768466866!3d37.773972570889594!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808f7e3b8b22e1f3%3A0x8224a32d477ec34c!2sGolden%20Gate%20Bridge!5e0!3m2!1sen!2sus!4v1634366169634!5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
                'policies' => 'No smoking, No parties',
                'banner_image' => 'serene-villa-banner.jpg',
                'tenancy_agreement' => 'serene-villa-tenancy-agreement.pdf',
                'corporate_documents' => 'serene-villa-corporate-documents.zip',
                'identity_documents' => 'serene-villa-identity-documents.zip',
                'proof_of_ownership' => 'serene-villa-proof-of-ownership.pdf',
                'isActive' => 1,
                'isVerified' => 1,
                'isBanned' => 0,
                'nearby_locations' => 'Golden Gate Bridge, Alcatraz Island',
            ],
            [
                'vendor_id' => 2,
                'name' => 'Mountain Retreat',
                'slug' => 'mountain-retreat-6',
                'description' => 'Experience tranquility in this cozy mountain retreat surrounded by majestic peaks and pristine wilderness.',
                'property_type_id' => 3, // Assuming 3 represents Mountain Retreat in your property type table
                'pay_in_property' => 1,
                'primary_number' => '1234567890',
                'secondary_number' => '0987654321',
                'primary_email' => 'info@mountainretreat.com',
                'secondary_email' => 'reservations@mountainretreat.com',
                'address' => '789 Pine Street',
                'city_id' => 3, // Assuming 3 represents a city in your city table
                'country' => 'United States',
                'zip' => '98765',
                'location_iframe' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3168.3762083192897!2d-118.28192668466715!3d34.02016147060984!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c75ddc27da13%3A0xe22fdfa3f5ad12b1!2sLos%20Angeles%2C%20CA%2C%20USA!5e0!3m2!1sen!2s!4v1634372005259!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
                'policies' => 'Pets allowed with additional fee, No loud music after 10pm',
                'banner_image' => 'mountain-retreat-banner.jpg',
                'tenancy_agreement' => 'mountain-retreat-tenancy-agreement.pdf',
                'corporate_documents' => 'mountain-retreat-corporate-documents.zip',
                'identity_documents' => 'mountain-retreat-identity-documents.zip',
                'proof_of_ownership' => 'mountain-retreat-proof-of-ownership.pdf',
                'isActive' => 1,
                'isVerified' => 1,
                'isBanned' => 0,
                'nearby_locations' => 'Ski Resort, National Park',
            ],
            [
                'vendor_id' => 3,
                'name' => 'Seaside Retreat',
                'slug' => 'seaside-retreat-5',
                'description' => 'Relax and unwind in this charming seaside retreat overlooking the sparkling ocean and sandy beaches.',
                'property_type_id' => 4, // Assuming 4 represents Seaside Retreat in your property type table
                'pay_in_property' => 1,
                'primary_number' => '1234567890',
                'secondary_number' => '0987654321',
                'primary_email' => 'info@seasideretreat.com',
                'secondary_email' => 'reservations@seasideretreat.com',
                'address' => '456 Beach Boulevard',
                'city_id' => 4, // Assuming 4 represents a city in your city table
                'country' => 'United States',
                'zip' => '54321',
                'location_iframe' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3369.7570610785056!2d-118.41822868491568!3d33.97178708063625!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2a4d8f32c6b19%3A0x2bba4116b56ab3dd!2sSanta%20Monica%2C%20CA%2C%20USA!5e0!3m2!1sen!2s!4v1634378498339!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
                'policies' => 'No smoking, No pets allowed',
                'banner_image' => 'seaside-retreat-banner.jpg',
                'tenancy_agreement' => 'seaside-retreat-tenancy-agreement.pdf',
                'corporate_documents' => 'seaside-retreat-corporate-documents.zip',
                'identity_documents' => 'seaside-retreat-identity-documents.zip',
                'proof_of_ownership' => 'seaside-retreat-proof-of-ownership.pdf',
                'isActive' => 1,
                'isVerified' => 1,
                'isBanned' => 0,
                'nearby_locations' => 'Santa Monica Pier, Venice Beach',
            ],
            [
                'vendor_id' => 4,
                'name' => 'Rustic Cabin',
                'slug' => 'rustic-cabin-4',
                'description' => 'Escape to nature in this charming rustic cabin nestled in the woods, offering a cozy retreat from the hustle and bustle of city life.',
                'property_type_id' => 5, // Assuming 5 represents Rustic Cabin in your property type table
                'pay_in_property' => 1,
                'primary_number' => '1234567890',
                'secondary_number' => '0987654321',
                'primary_email' => 'info@rusticcabin.com',
                'secondary_email' => 'reservations@rusticcabin.com',
                'address' => '789 Forest Lane',
                'city_id' => 5, // Assuming 5 represents a city in your city table
                'country' => 'United States',
                'zip' => '67890',
                'location_iframe' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d27077.765134674555!2d-122.40986608308394!3d37.77492949925002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808f7e3b8b22e1f3%3A0x8c2c7db0a7a41039!2sSan%20Francisco%2C%20CA%2C%20USA!5e0!3m2!1sen!2s!4v1634379058822!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
                'policies' => 'No smoking, No parties',
                'banner_image' => 'rustic-cabin-banner.jpg',
                'tenancy_agreement' => 'rustic-cabin-tenancy-agreement.pdf',
                'corporate_documents' => 'rustic-cabin-corporate-documents.zip',
                'identity_documents' => 'rustic-cabin-identity-documents.zip',
                'proof_of_ownership' => 'rustic-cabin-proof-of-ownership.pdf',
                'isActive' => 1,
                'isVerified' => 1,
                'isBanned' => 1,
                'nearby_locations' => 'Hiking Trails, Fishing Spot',
            ],
            [
                'vendor_id' => 1,
                'name' => 'Urban Loft',
                'slug' => 'urban-loft-3',
                'description' => 'Experience modern city living in this stylish urban loft located in the heart of downtown.',
                'property_type_id' => 6, // Assuming 6 represents Urban Loft in your property type table
                'pay_in_property' => 1,
                'primary_number' => '1234567890',
                'secondary_number' => '0987654321',
                'primary_email' => 'info@urbanloft.com',
                'secondary_email' => 'reservations@urbanloft.com',
                'address' => '123 Main Street, Apt 101',
                'city_id' => 6, // Assuming 6 represents a city in your city table
                'country' => 'United States',
                'zip' => '54321',
                'location_iframe' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3870.173339635332!2d-122.41941898462639!3d37.774929799652336!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80858099cf983def%3A0xb82d62f9b9b0857b!2sSan%20Francisco%2C%20CA%2094105%2C%20USA!5e0!3m2!1sen!2s!4v1634379491188!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
                'policies' => 'No smoking, No pets allowed',
                'banner_image' => 'urban-loft-banner.jpg',
                'tenancy_agreement' => 'urban-loft-tenancy-agreement.pdf',
                'corporate_documents' => 'urban-loft-corporate-documents.zip',
                'identity_documents' => 'urban-loft-identity-documents.zip',
                'proof_of_ownership' => 'urban-loft-proof-of-ownership.pdf',
                'isActive' => 1,
                'isVerified' => 1,
                'isBanned' => 1,
                'nearby_locations' => 'Shopping District, Restaurants',
            ],
            [
                'vendor_id' => 2,
                'name' => 'Luxury Penthouse',
                'slug' => 'luxury-penthouse-2',
                'description' => 'Indulge in luxury living with breathtaking views from this exquisite penthouse in the sky.',
                'property_type_id' => 7, // Assuming 7 represents Luxury Penthouse in your property type table
                'pay_in_property' => 1,
                'primary_number' => '1234567890',
                'secondary_number' => '0987654321',
                'primary_email' => 'info@luxurypenthouse.com',
                'secondary_email' => 'reservations@luxurypenthouse.com',
                'address' => '789 High Street, Unit 2201',
                'city_id' => 7, // Assuming 7 represents a city in your city table
                'country' => 'United States',
                'zip' => '12345',
                'location_iframe' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2647.2893502767383!2d-118.41102168483546!3d34.06188527960228!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c75ddc27da13%3A0x8224a32d477ec34c!2sLos%20Angeles%2C%20CA%2C%20USA!5e0!3m2!1sen!2s!4v1634380002760!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
                'policies' => 'No smoking, No parties',
                'banner_image' => 'luxury-penthouse-banner.jpg',
                'tenancy_agreement' => 'luxury-penthouse-tenancy-agreement.pdf',
                'corporate_documents' => 'luxury-penthouse-corporate-documents.zip',
                'identity_documents' => 'luxury-penthouse-identity-documents.zip',
                'proof_of_ownership' => 'luxury-penthouse-proof-of-ownership.pdf',
                'isActive' => 1,
                'isVerified' => 1,
                'isBanned' => 1,
                'nearby_locations' => 'Shopping Mall, Fine Dining Restaurants',
            ],
            [
                'vendor_id' => 4,
                'name' => 'Countryside Cottage',
                'slug' => 'countryside-cottage-1',
                'description' => 'Escape to the serene countryside in this charming cottage surrounded by rolling hills and scenic landscapes.',
                'property_type_id' => 8, // Assuming 8 represents Countryside Cottage in your property type table
                'pay_in_property' => 1,
                'primary_number' => '1234567890',
                'secondary_number' => '0987654321',
                'primary_email' => 'info@countrysidecottage.com',
                'secondary_email' => 'reservations@countrysidecottage.com',
                'address' => '123 Country Lane',
                'city_id' => 8, // Assuming 8 represents a city in your city table
                'country' => 'United States',
                'zip' => '54321',
                'location_iframe' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d198042.22804056757!2d-75.14928484177272!3d40.03174494459136!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c7005d98c1d46b%3A0xa0b328d3aa7f9783!2sPennsylvania%2C%20USA!5e0!3m2!1sen!2s!4v1634380701320!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
                'policies' => 'No smoking, No pets allowed',
                'banner_image' => 'countryside-cottage-banner.jpg',
                'tenancy_agreement' => 'countryside-cottage-tenancy-agreement.pdf',
                'corporate_documents' => 'countryside-cottage-corporate-documents.zip',
                'identity_documents' => 'countryside-cottage-identity-documents.zip',
                'proof_of_ownership' => 'countryside-cottage-proof-of-ownership.pdf',
                'isActive' => 1,
                'isVerified' => 1,
                'isBanned' => 1,
                'nearby_locations' => 'Nature Trails, Vineyards',
            ],
        ];

        foreach ($hotels as $hotel) {
            DB::table('hotels')->insert($hotel);
        }
    }
}
